repos:
  - repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
      - id: black
        args: ['--skip-string-normalization']
        language_version: python3.7

  - repo: https://github.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        args: [--config, .flake8.ini]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: trailing-whitespace
        language_version: python3.7
      - id: end-of-file-fixer
        language_version: python3.7
      - id: debug-statements
        language_version: python3.7

  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.7.0
    hooks:
      - id: seed-isort-config
        language_version: python3.7


  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.12
    hooks:
      - id: isort
        language_version: python3.7
